### PR TITLE
Rework directive to integrate better with ngModel

### PR DESCRIPTION
**Pull request by mpolichette**
Hey! Thanks for starting this project out.  

I was having a few issues using the angular medium editor and have addressed the following issues with this pull request.

1.  Unsafe re-creation of Medium Editor.  I removed the memory leak caused by multiple editors being initialized for a single element.  This was breaking keyboard commands every *other* time you emptied the buffer. (cmd+b would fire for each one, and when there was an even number of editors, they would cancel eachother out).

2.  Unable to use ngModel validators like `required` because even an empty buffer was setting the model to `<p><br><p>`   This still happens, but I've written an ngModel.$isEmpty which detects an empty buffer and reports it so.

3. Removed multiple ways of setting options.  If we are creating a watcher for bindOptions either way, we might as well just use that watcher.  (both `options` and `bind-options` were being evaluated every time `bind-options` changed anyway)

I took a bit of a large refactor on the codebase for this one, so I hope thats not too bothersome, let me know if there is a reason you don't like this solution.  I don't think I have any regressions, it appears like the placeholder and toolbar are performing correctly in the evergreen browsers I tested.

Thanks!

### CODE REVIEW

**Comment by mpolichette** [comment]
Note: This PR can also close a number of other issues and PRs:

**Comment by maciej-gurban** [comment]
Hi. Any chance this would be merged any time soon?

**Comment by thijsw** [comment]
+1

Many thanks for this great work! I've prepared a pre-release 1.1.0 with this code (was unable to merge directly unfortunately). As mentioned, if some people would be willing to test this, would be appreciated :)

https://github.com/thijsw/angular-medium-editor/tree/1.1.0

**Comment by simison** [comment]
Seems like readme now requires updates. Figuring some things out first and sending it your way soon.

**Comment by simison** [comment]
Been testing this now and seems to work great.

Thanks @mpolichette!

**Comment by thijsw** [comment]
I will close this PR now, the improvements seem to work great! Possible changes to README are still welcome though

**Pull request closed without merging**
