### PR TITLE
update to latest stable version of medium-editor (5.7)

### PR DESCRIPTION
**Pull request by AlexandreKilian**

### CODE REVIEW

**Comment by simison** [comment]
Did you test this thoroughly or do you need more +1's?

**Comment by AlexandreKilian** [comment]
I tested it a bit with a few different applications, there were no breaking changes, but it doesn't hurt if others try it with their implementation...

**Comment by simison** [comment]
Been testing this for a few days and it seems to work well.

**Comment by barryvdh** [comment]
Seems to be working..
:+1:

**Comment by barryvdh** [comment]
But at least the placeholder option has changed, so needs a version bump to 0.2.0

**Comment by thijsw** [comment]
This one became by redundant by releasing the code of #34 in upcoming release 1.1.0

**Pull request closed without merging**
