### PR TITLE
Set html content with editor setContent(), supports textarea

### PR DESCRIPTION
**Pull request by toddkittredge**
Resolves issue... Textarea div not populated with ngModel.$viewValue when present #71

### CODE REVIEW

**Comment by thijsw** [comment]
Thanks for reporting this issue, and providing a fix as well! Will merge straight away if minified version is included as well :)

**Comment by toddkittredge** [comment]
Happy to help... "if minified version is included", do you want a push to /dist or will you generate that on your end?

**Comment by thijsw** [comment]
After you've edited the files in `src/` (which you already did), you can run `grunt` (without arguments) to generate the minified production-ready version of the library. :)

**Comment by toddkittredge** [comment]
Already tested build here, will promote result to /dist !

**Comment by toddkittredge** [comment]
Was confusing procedural comments in YABWE regarding pushing (or not as is the case) to /dist...

Good to go!

**Comment by thijsw** [comment]
Nevermind. Thanks for your contribution!

**Pull request merged**
