### PR TITLE
Ng disabled

### PR DESCRIPTION
**Pull request by MCeddy**
Hello. I've added a new bindable attribute ng-disabled to disable the editor behavior easily.

best regards

MCeddy :)

### CODE REVIEW

**Comment by simison** [comment]
I like this! @thijsw thoughts?

@MCeddy this would need to be resolved against current master, there are quite a few changes there.

**Comment by MCeddy** [comment]
Sorry, but currently there isn't time for re-implementing this feature :-\

**Comment by thijsw** [comment]
I like this feature as well, looks a lot like #17. I try to resolve the merge conflicts and look into releasing this

**Comment by MCeddy** [comment]
Okay. Thanks

**Comment by thijsw** [comment]
I don't see the methods `activate` and `deactivate` anymore in the API of Medium editor, is this functionality still relevant? See [API](/yabwe/medium-editor#api)

**Comment by simison** [comment]
You're right, it got deprecated:

- https://github.com/yabwe/medium-editor/blob/master/CHANGES.md#4120--2015-06-01
- https://github.com/yabwe/medium-editor/blob/82c57a28127a10e85ad676f4e17d11b77e608c35/UPGRADE-5.md#activate

**Comment by simison** [comment]
I think the bottom line would be that angular-medium-editor doesn't comply well according to Angular's [form controller](https://docs.angularjs.org/api/ng/type/form.FormController) and [input](https://docs.angularjs.org/api/ng/directive/input)/[textarea](https://docs.angularjs.org/api/ng/directive/textarea) directives.

**Comment by thijsw** [comment]
Yes, that's right. I think it is best to have some separate PRs in which changes are proposed that intent to to mimic the behaviour (ng-required, ng-minlength, ng-maxlength, ng-pattern, ng-change, ng-trim) of AngularJS's native input directives as much as possible.

**Comment by simison** [comment]
Absolutely. I'll add a todo.

**Comment by simison** [comment]
@thijsw btw feel free to add me as a contributor. I can't promise anything but could at least review pull requests when you're busy. I forked this directive to use at @Trustroots and it's pretty important part of our stack, so I have strong interest to continue working on this. :-)

**Comment by thijsw** [comment]
@simison Will do, was already considering it :) Thanks for your active involvement in the project!

**Pull request closed without merging**
